name: Publish npm package 

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout emscope
        uses: actions/checkout@v6
        with:
          path: emscope

      - name: Set up Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Build emscope package
        run: |
          pushd emscope
          npm ci
          npm run build
          popd

      - name: Test emscope executable
        run: |
          ./emscope/dist/emscope --version

          

      - name: Publish emscope package
        run: |
          pushd emscope
          cp docs/README-npm.md README.md
          npm config list
          npm publish --access public
          popd        
